version: 2.0
jobs:
  build:
    docker:
      - image: mirok/neuronmi:latest
    working_directory: /home/fenics/nEuronMI
    steps:
      - run:
          name: Test mesh
          command: |
                python -m unittest discover test/mesh
